baseURL = "https://www.cremeitup.in/"
languageCode = "en-in"
title = "Crème It Up | Premium Bakery & Baking Classes"
summaryLength = 30
paginate = 10
enableRobotsTXT = true

[params]
  description = "Crème It Up is a premium bakery and baking workshop studio in Chandigarh. Custom cakes, pastries, breads, and hands-on baking classes by Chef Anushka Madaan. Serving Chandigarh, Mohali, and Panchkula."
  author = "Anushka Madaan"
  phone = "+91 6284392288"
  email = "Cremeitup@gmail.com"
  whatsapp = "916284392288"
  address = "Crème It Up Studio, Sector 46 C, Chandigarh"
  instagram = "https://www.instagram.com/creme.it_up"
  linktree = "https://linktr.ee/cremeitup"
  tagline = "Where baking dreams come true"
  locale = "en_IN"
  ogImage = "/images/og-default.png"

[params.seo]
  keywords = ["creme it up", "cremeitup", "bakery in chandigarh", "best bakery chandigarh", "baking classes chandigarh", "custom cakes chandigarh", "cake shop chandigarh", "pastry shop chandigarh mohali", "bakers near me chandigarh mohali panchkula", "baking workshop chandigarh", "french pastries chandigarh", "cake delivery chandigarh mohali panchkula", "cake delivery chandigarh","chef anushka madaan"]

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menus.main]]
    name = "Classes"
    url = "/classes/"
    weight = 3
  [[menus.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 4
  [[menus.main]]
    name = "Blog"
    url = "/blog/"
    weight = 5
  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
